apiVersion: v1
kind: Pod
metadata:
  name: hellok8s
  labels:
    name: hellok8s
spec:
  containers:
  - name: privateregistry
    image: mbiregistry.azurecr.io/hellok8s:latest
    ports:
    - containerPort: 8080
  imagePullSecrets:
  - name: acr-secret
