
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hellok8s
  name: hellok8s-svc
spec:
  ports:
    - name: httpport
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: hellok8s
  sessionAffinity: None
  type: NodePort